name: Auto-update Quartz

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update:
    name: Auto-update Quartz
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: |
          pnpm install
      - name: Update Quartz
        run: |
          git remote add upstream https://github.com/jackyzha0/quartz.git
          git fetch upstream
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if ! git pull --allow-unrelated-histories --no-rebase --autostash -s recursive -X ours --no-edit upstream v4; then
            exit 1
          fi
      - name: Push changes and create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          title: Update Quartz to latest version
          branch: chore/update-quartz
          body: |
            This PR updates Quartz to the latest version using `git merge`. Double-check the changes and merge if everything looks good.

            <small>Raised automatically by [the auto-update Actions workflow](https://github.com/arashnrim/garden/blob/main/.github/workflows/auto-update.yml).</small>
          assignees: arashnrim
          reviewers: arashnrim
          labels: dependencies,enhancement
